FROM golang:1.14-alpine AS development

ENV PROJECT_PATH=/grpc-test
ENV PATH=$PATH:$PROJECT_PATH/build
ENV CGO_ENABLED=0
ENV GO_EXTRA_BUILD_ARGS="-a -installsuffix cgo"

RUN apk add --no-cache ca-certificates make git bash alpine-sdk nodejs nodejs-npm

RUN mkdir -p $PROJECT_PATH
COPY . $PROJECT_PATH
WORKDIR $PROJECT_PATH

RUN make dev-requirements
RUN make client-orig

FROM alpine:latest AS production

RUN apk --no-cache add ca-certificates
COPY --from=development /grpc-test/build/greeter-client-orig /usr/bin/greeter-client
ENTRYPOINT ["/usr/bin/greeter-client"]
